#spring.application.name=TodoApi

server:
  port:8080

spring:
  application:
    name: TodoApi
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    database: mysql

  springdoc:
    swagger-ui:
      path: /myapi.html