#spring.application.name=TodoApi

server:
  port:8181

spring:
  application:
    name: TodoApi
  datasourece:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql

  springdoc:
    swagger-ui:
      path: /myapi.html